config/routes.rb
Bummer::Application.routes.draw do
  
  match '/search' => 'search#index'

  root to: 'pages#show', id: 'home'

  devise_for :users, controllers: { 
    sessions: 'sessions',
    passwords: 'passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_for :users, controllers: { 
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :records, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :relationships, only: [:create, :destroy]
  resources :discussions, only: [:create, :show]
  resources :comments, only: [:create]

  resources :discussions do
    resources :comments
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/views/shared/_discussions.html.haml
- if @discussions_popular.any? || @discussions_recent.any?
  %section.block#discussions
    %header
      .title
        Discussions
      .icon
      .gradient
    .content
      / TODO: make longer if one of row doesnot exists
      .discus
        - if @discussions_popular.any?
          .first
            .title
              Most popular
            %ul
              - @discussions_popular.each do |discussion|
                %li
                  = link_to discussion.record.name, discussion, class: 'name'
                  = link_to "(#{pluralize(discussion.comments.count, 'comment')})", '#', class: 'comments'
        - if @discussions_recent.any?
          .second
            .title
              Recent added
            %ul
              - @discussions_recent.each do |discussion|
                %li
                  = link_to discussion.record.name, discussion_path(discussion, anchor: 'comments'), class: 'name'
                  = link_to "(#{pluralize(discussion.comments.count, 'comment')})", '#', class: 'comments'

app/views/shared/_profile.html.haml
%section.block.first#profile
  %header
    .avatar
      = link_to image_tag('avatar.png'), current_user
    .info
      .name
        = link_to current_user.username, current_user
      .status
        = current_user.records.last.name
    .counts
      %div
        .number
          = current_user.records.count
        = 'Record'.pluralize
      %div
        .number
          = current_user.discussions.count
        = 'Discussion'.pluralize
    .gradient
  - if current_user.followed_users.any? || current_user.followers.any? 
    .content
      .ff
        - if current_user.followed_users.any?
          .following
            .turnabout
              .alt
                = link_to following_user_path(current_user) do
                  %span
                    = current_user.followed_users.count
                  Following
              .wrapper
                - if current_user.followed_users.count > 4
                  .left.hide
                %ul
                  - current_user.followed_users.each do |user|
                    %li
                      .avatar
                        = link_to image_tag('test-avatar.png'), user
                      .hover
                - if current_user.followed_users.count > 4
                  .right
        - if current_user.followers.any?
          .followers
            .turnabout
              .alt
                = link_to followers_user_path(current_user) do
                  %span
                    = current_user.followers.count
                  Followers
              .wrapper
                - if current_user.followers.count > 4
                  .left.hide
                %ul
                  - current_user.followers.each do |user|
                    %li
                      .avatar
                        = link_to image_tag('test-avatar.png'), user
                      .hover
                - if current_user.followers.count > 4
                  .right